jobs:
  build:
    continue-on-error: ${{ matrix.experimental }}
    env:
      ORG_GRADLE_PROJECT_bladePluginVersion: ${{ matrix.bladePlugin }}
      ORG_GRADLE_PROJECT_phpPluginVersion: ${{ matrix.phpPlugin }}
      ORG_GRADLE_PROJECT_platformVersion: ${{ matrix.platform }}
    name: Build
    needs: test
    outputs:
      artifact: ${{ steps.properties.outputs.artifact }}
      name: ${{ steps.properties.outputs.name }}
      version: ${{ steps.properties.outputs.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup Gradle Dependencies Cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle',
          'gradle.properties') }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Setup Gradle Wrapper Cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Build Plugin
      run: ./gradlew buildPlugin
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: plugin-artifact
        path: ./build/distributions/${{ steps.properties.outputs.artifact }}
    strategy:
      matrix:
        include:
        - bladePlugin: 183.3795.24
          experimental: false
          phpPlugin: 183.4886.46
          platform: 2018.3.5
  gradleValidation:
    name: Gradle Wrapper
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.3
  test:
    continue-on-error: ${{ matrix.experimental }}
    env:
      ORG_GRADLE_PROJECT_bladePluginVersion: ${{ matrix.bladePlugin }}
      ORG_GRADLE_PROJECT_phpPluginVersion: ${{ matrix.phpPlugin }}
      ORG_GRADLE_PROJECT_platformVersion: ${{ matrix.platform }}
    name: Test
    needs: gradleValidation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Setup Gradle Dependencies Cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle',
          'gradle.properties') }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Setup Gradle Wrapper Cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Run Linters and Test
      run: ./gradlew check
    - continue-on-error: true
      name: Verify Plugin
      run: ./gradlew verifyPlugin
    strategy:
      matrix:
        include:
        - bladePlugin: 191.7141.5
          experimental: true
          phpPlugin: 191.7141.52
          platform: 2019.1.3
        - bladePlugin: 183.3795.24
          experimental: false
          phpPlugin: 183.4886.46
          platform: 2018.3.5
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
